spring.application.name=cachingproject
server.port=8081
#spring.data.redis.url=rediss://default:${REDIS_PASSWORD}@redis-10378.crce196.sa-east-1-2.ec2.cloud.redislabs.com:10378/0
#spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.host=localhost
spring.data.redis.port=6379